### ISSUE TITLE
inflation into moose

### ISSUE THREAD

**Issue by icklekitten** [vrurg/MooX-AttributeFilter#1]
You might be able to use this:

https://metacpan.org/release/KITTEN/MooseX-AttributeFilter-0.01

**Comment by vrurg** [comment]
This is fantastic! Thanks!

Unfortunately, I'm currently somewhat busy with another project and won't be able to make use of your work in the nearest future. But I'm happy to know that this job is now awaiting for me! :)

**Comment by icklekitten** [comment]
Saw you released a trial version. Probably shouldn't have an explicit dependency on MooseX::AttributeFilter.

**Comment by vrurg** [comment]
It was picked by Dist::Zilla AutoPrereqs plugin. Fixed by excluding all MooseX:: prefixes. 

The v0.002 is now released. Unfortunately, documentation was totally forgotten and left unchanged. Will publish the fix tomorrow.

Thanks for all your help! It was priceless!

**Comment by icklekitten** [comment]
No problem!

I should also do better documentation for my module.
