### ISSUE TITLE
use in roles?

### ISSUE THREAD

**Issue by icklekitten** [vrurg/MooX-AttributeFilter#2]
Is not tested and not documented. Is it supported?

I make Moose version of this module and support roles. Maybe my test useful to you?

https://github.com/icklekitten/MooseX-AttributeFilter/blob/master/t/901-roles.t

Will need only some small modificiations for test case work with Moo.

**Comment by vrurg** [comment]
How. Come. Did. I. Forget. About. Roles??? Thanks for the report! I'll see if your test code could be used or some other approach would be needed to unify testing of different cases (class/role/inflated class/inflated role).
