### ISSUE TITLE
filter not allowed for is=>'ro'

### ISSUE THREAD

**Issue by icklekitten** [vrurg/MooX-AttributeFilter#5]
Having a filter for is=>'ro' should be allowed.

First reason: filter can still be used for constructor.

Second reason:

	has xyz => (
		is      => 'ro',
		filter  => sub { ... },
		writer  => '_change_xyz',
	);

**Comment by vrurg** [comment]
Any of the two is convincing enough. I'm at TPC2018 currently. But the change is minimal, as soon as I get straight 15 spare minutes it'll be published.

---
Regards,
Vadim Belman

Sent from iPad

17 черв. 2018 р. о 15:18 Little Princess Kitten ♥ <notifications@github.com> пише:

**Comment by vrurg** [comment]
Fixed in version 0.003
